export const SOCIAL_ICONS = [
  { name: 'Globe', label: '网站/通用' },
  { name: 'Github', label: 'GitHub' },
  { name: 'MessageCircle', label: '微信/聊天' },
  { name: 'MessageSquare', label: '论坛/Discord' },
  { name: 'Rss', label: 'RSS' },
  { name: 'Mail', label: '邮箱' },
  { name: 'Twitter', label: 'Twitter/X' },
  { name: 'Video', label: '视频/YouTube' },
  { name: 'Camera', label: 'Instagram/摄影' },
  { name: 'Music', label: '音乐/网易云' },
  { name: 'Linkedin', label: 'LinkedIn' },
  { name: 'BookOpen', label: '博客/阅读' },
  { name: 'Heart', label: '赞助/喜欢' },
  { name: 'Coffee', label: '赞助/咖啡' },
  { name: 'ExternalLink', label: '外部链接' },
  { name: 'Link2', label: '链接' },
  { name: 'Share2', label: '分享' },
  { name: 'Send', label: 'Telegram/发送' },
  { name: 'Phone', label: '电话' },
  { name: 'MapPin', label: '地址' },
]